#!/bin/bash
echo "┎────────────────────────────────────────────────────────"
echo "│    Running docker build command"
echo "│    Image Name: $IMAGE_NAME"
echo "│    Dockerfile Path: $DOCKERFILE_PATH"
echo "│    Current Working Dir: $(pwd)"
echo "┖────────────────────────────────────────────────────────"

docker build \
    --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    --build-arg VCS_REF=`git rev-parse --short HEAD` \
    -f ../../$DOCKERFILE_PATH \
    -t $IMAGE_NAME \
    ../..