#!/bin/bash

docker build \
    --build-arg VCS_REF=`git rev-parse - shord HEAD` \
    --build-arg BUILD_DATE=`date -u + "%Y-%m-%dT%H:%M%SZ"` \
    --build-arg BUILD_VERSION="1.0.0"
    -t $IMAGE_NAME .