# Author: Kabir Kwatra <kabir@kwatra.me>

stages: [build]

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >
      for containerfile_path in $(ls .github/containerfiles/*.Containerfile); do
        containerfile_name=${containerfile_path##*/}
        container_tag=${containerfile_name%%.*}
        container_fulltag="$CI_REGISTRY_IMAGE:$container_tag"
        echo "Building $containerfile_name with tag $container_fulltag"
        /kaniko/executor \
          --context $CI_PROJECT_DIR \
          --dockerfile $containerfile_path \
          --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
          --build-arg VCS_REF=`git rev-parse --short HEAD` \
          --build-arg OCI_SRC_URL=$CI_PROJECT_URL \
          --destination $container_fulltag
      done
